docs(egjs-flicking): tutorial doc contains link that 404s
naver/egjs-flicking pull request #799
Opened 2023-04-18 07:36 UTC by seungdeok

Ref #798

## Issue

798

## Details

- before
```
# egjs-flicking/docs/docs/tutorials/listening-to-events.mdx, 28th lines
You can listen to Flicking's events with [Flicking#on](api/Flicking#on)
```

- after
```
# egjs-flicking/docs/docs/tutorials/listening-to-events.mdx, 28th lines
You can listen to Flicking's events with [Flicking#on](useBaseUrl(api/Flicking#on))
```

2023-04-18 07:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/naver/egjs-flicking?pullRequest=799) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/naver/egjs-flicking?pullRequest=799) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/naver/egjs-flicking?pullRequest=799) it.</sub>

2023-04-18 07:43 UTC, malangfox approved these changes
Thank you for your contribution!
I think the missing `on` and `off` in the Methods in the documentation is the cause of the issue you left.
We'll fix that and then review the PR you left.

2023-04-18 09:53 UTC, WoodNeck requested changes

2023-04-18 13:10 UTC, malangfox commented
We fixed an issue that methods including `on` and `off` were not displaying correctly on the Flicking documentation page.
After we fixed this, the page you left in the issue appears to be working properly.

Separately, we'll review the PR you left to see if it can be applied.

2023-04-18 23:22 UTC, seungdeok commented on docs/docs/tutorials/listening-to-events.mdx
> +You can listen to Flicking's events with [Flicking#on](useBaseUrl(api/Flicking#on))
@WoodNeck 
Thanks you for the feedback.
I did "commit" referring to the feedback.

2023-04-19 04:21 UTC, WoodNeck approved these changes
LGTM, thanks for your PR!

2023-04-19 11:17 UTC, malangfox approved these changes

2023-04-21 04:17 UTC, daybrush approved these changes
LGTM

2023-04-21 05:18 UTC, merged